# -*- coding: utf-8 -*-
"""ai_interpreter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1omoxrZKHwqfMFmSq5RvFuLbHDYhB2LAh
"""

import openai

def interpret_regression(results):

    summary = results.summary().as_text()

    prompt = f"""
Explain the following regression results in simple academic language:

{summary}
"""

    response = openai.ChatCompletion.create(
        model="gpt-4",
        messages=[{"role":"user","content":prompt}]
    )

    return response["choices"][0]["message"]["content"]