# -*- coding: utf-8 -*-
"""analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yRK20R_ahJxj2VzAhDm49IfLOjMESwF4
"""

import statsmodels.api as sm

def run_correlation(df):

    return df.corr()


def run_regression(df, y, X):

    X_data = df[X]
    X_data = sm.add_constant(X_data)

    model = sm.OLS(df[y], X_data).fit()

    return model