# -*- coding: utf-8 -*-
"""assumption_tests.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18XYqcda8IUDXgKgCOageaKsxJ3avA9xE
"""

import statsmodels.stats.api as sms
from statsmodels.stats.outliers_influence import variance_inflation_factor
import pandas as pd

def regression_assumptions(model, df, X):

    results = {}

    # Heteroskedasticity
    test = sms.het_breuschpagan(model.resid, model.model.exog)

    results["Heteroskedasticity p-value"] = test[1]

    # Multicollinearity

    X_data = df[X]

    vif = pd.DataFrame()

    vif["Variable"] = X_data.columns
    vif["VIF"] = [variance_inflation_factor(X_data.values, i) for i in range(len(X_data.columns))]

    results["VIF"] = vif

    return results