# -*- coding: utf-8 -*-
"""code_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYZL4pnhMIZBWabKoYJk_YgFnNj4yEOc
"""

def generate_regression_code(y, X):

    code = f"""

import statsmodels.api as sm

y = df['{y}']
X = df[{X}]

X = sm.add_constant(X)

model = sm.OLS(y, X).fit()

print(model.summary())

"""

    return code