# -*- coding: utf-8 -*-
"""profiler.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rbDs_wxJZO8GCx37BNNKnntqrMkRsy5z
"""

import pandas as pd

def profile_data(df):

    summary = {}

    summary["Observations"] = df.shape[0]
    summary["Variables"] = df.shape[1]

    numeric = df.select_dtypes(include="number").columns
    categorical = df.select_dtypes(exclude="number").columns

    summary["Numeric Variables"] = len(numeric)
    summary["Categorical Variables"] = len(categorical)

    missing = df.isna().sum().sum()

    summary["Missing Values"] = missing

    return summary