# -*- coding: utf-8 -*-
"""recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MANa-gLYpPgOq8VujVB_A-YVcsY6HSei
"""

def recommend_methods(df):

    methods = []

    numeric = df.select_dtypes(include="number").columns

    if len(numeric) >= 2:
        methods.append("Correlation Analysis")

    if len(numeric) >= 3:
        methods.append("Multiple Linear Regression")

    if df.select_dtypes(include="object").shape[1] > 0:
        methods.append("Chi-Square Test")

    methods.append("Clustering")

    return methods