# -*- coding: utf-8 -*-
"""report_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a9gwHE_Z3LZgs66XkOu5Zm_v-mNasMvQ
"""

from docx import Document

def generate_report(results, interpretation):

    doc = Document()

    doc.add_heading("Statistical Analysis Report")

    doc.add_heading("Regression Results")

    doc.add_paragraph(results.summary().as_text())

    doc.add_heading("Interpretation")

    doc.add_paragraph(interpretation)

    path = "report.docx"

    doc.save(path)

    return path