# -*- coding: utf-8 -*-
"""visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xzt9Ok6CF4mQZ-jo86obip5Oeb-sIjov
"""

import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

def plot_corr_heatmap(corr):

    fig = px.imshow(corr, text_auto=True)

    return fig


def regression_plots(model):

    residuals = model.resid
    fitted = model.fittedvalues

    fig1 = plt.figure()

    sns.scatterplot(x=fitted, y=residuals)

    plt.axhline(0)

    plt.title("Residual Plot")

    fig2 = plt.figure()

    sns.histplot(residuals, kde=True)

    plt.title("Residual Distribution")

    return fig1, fig2